ppl = {
'Agnes Rut Ásgeirsdóttir': '',
'Arndís prufa': 'Arndís',
'Aron Freyr Kristjánsson': 'Aron',
'Björg Hákonardóttir': 'Björg',
'Breki prufa': 'Breki',
'Daníel Pétursson': 'Daníel',
'Davíð Arnljótur Karlsson': 'Davíð',
'Friðberg Reynir Traustason': 'Friðberg',
'Guðbjartur Máni Gíslason': 'G. Máni',
'Guðni Þór Björnsson': 'Guðni',
'Gunnar Kristinn Þórðarson': 'Gunnar',
'Harpa Mjöll Þórsdóttir': 'Harpa',
'Hrafn Ingi Jóhannsson': 'Hrafn',
'Hrafnhildur S Benediktsdóttir': 'Hrafnhildur',
'Ingibjörg Rún Jóhannesdóttir': 'Ingibjörg Rún',
'Íris Hildur Birgisdóttir': 'Íris',
'Ísak Örn Ívarsson': 'Ísak',
'Jón Arnar Björnsson': 'Nonni',
'Jón Egill Eyþórsson': 'Jón Egill',
'Karl Héðinn Kristjánsson': 'Kalli',
'Kolfinna Kristjánsdóttir': 'Kolfinna',
'Kristín Anna Ólafsdóttir': 'Kristín',
'Kristján Ingi Rúnarsson': 'Kristján Ingi',
'Kristján Kristjánsson': 'Kristján K',
'KVK 1': '',
'Lena María Brynjarsdóttir': 'Lena',
'Óðinn Dagur Bjarnason': 'Óðinn',
'Ólafur Árni Jónsson': 'Ólafur',
'Ragnar Ingi Karlsson': 'Ragnar Ingi',
'Ragnheiður Lindudóttir': 'Ragnheiður',
'Rakel Ketilsdóttir': 'Rakel',
'Róbert Steinar Hjálmarsson': 'Róbert',
'Rósa María Friðriksdóttir': 'Rósa',
'Sara Bergmann Valtýsdóttir': 'Sara',
'Sesselja Hansen Daðadóttir': 'Sesselja',
'Sigríður Eyrún Sigurjónsdóttir': 'Sigga',
'Sigrún Erla Lárusdóttir': 'Sigrún',
'Sigurjón Már Markússon': 'Sigurjón',
'Silja Hjaltadóttir': 'Silja',
'Sindri Rafn Guðmundsson': 'Sindri Rafn',
'Sindri Viborg': 'Sindri V',
'Stefanía Katrín prufa': 'Stefanía K',
'Stefanía Smáradóttir': 'Stefanía Smáradóttir',
'Sveinbjörn Skúlason': 'Sveinbjörn',
'Úlfar Gunnarsson': 'Úlfar',
'Valgerður Selma Lúthersdóttir': 'Valgerður',
'Þorvaldur Jóhannesson': 'Þorvaldur',
'Þórir Óskar Björnsson': 'Skari',
'Ævar Örn Erlendsson': 'Ævar',
'övantar': '',
}